#!/usr/bin/env bash
# postCreate.sh - Codespaces 起動後の初期セットアップ
# Terraform が使用する TF_VAR_ 変数を環境変数から転記する

set -euo pipefail

PROFILE_FILE="${HOME}/.bashrc"

# 環境変数のマッピング: <Codespace 環境変数名>=<TF_VAR_ 変数名(サフィックス)>
declare -A ENV_MAP=(
  [VULTR_API_KEY]="vultr_api_key"
  [DO_PAT]="do_pat"
  [VULTR_LABEL_PREFIX]="vultr_label_prefix"
  [VULTR_REGION]="vultr_region"
  [VKE_NODE_PLAN]="vke_node_plan"
  [VKE_HA_CONTROL_PLANE]="vke_ha_control_plane"
  [VKE_ENABLE_FIREWALL]="vke_enable_firewall"
  [DOMAIN]="domain"
  [GH_ORGANIZATION]="gh_organization"
  [GH_CLIENT_ID]="gh_client_id"
  [GH_CLIENT_SECRET]="gh_client_secret"
  [LE_ENVIRONMENT]="le_environment"
  [CODER_POSTGRESQL_SIZE]="coder_postgresql_size"
  [CODER_WORKSPACE_DEFAULT_SIZE]="coder_workspace_default_size"
)

echo "# TF_VAR_ variables auto-generated by postCreate.sh" >> "${PROFILE_FILE}"
for src_var in "${!ENV_MAP[@]}"; do
  tf_var="TF_VAR_${ENV_MAP[$src_var]}"
  if [[ -n "${!src_var:-}" ]]; then
    echo "export ${tf_var}=\"\${${src_var}}\"" >> "${PROFILE_FILE}"
    # 現在のシェルにも即時反映
    export "${tf_var}=${!src_var}"
  fi
done

echo "postCreate: TF_VAR_ 変数を ${PROFILE_FILE} に書き込みました。"

# deploy.sh に実行権限を付与
chmod +x "${CODESPACE_VSCODE_FOLDER:-/workspaces/coder-vke}/deploy.sh"
